### ISSUE TITLE
CSS完全居中

### ISSUE THREAD

**Issue by LiuShuangBill** [LiuShuangBill/blog-github#35]
## 1.对于父元素不固定高
```css
  .parent {
    padding: 20px;
  }
  .children {
    margin: 0 auto;
    width: 100px;
    height: 100px;
  }
```

## 2.绝对定位，固定宽高
```css
   .parent {
    position: relative;
    width: 200px;
    height: 200px;
  }
  .children {
    position: absolute;
    left: 50%;
    top: 50%;
    margin-left: -50px;
    margin-top: -50px;
    width: 100px;
    height: 100px;
  }
```

## 3.绝对定位，不固定宽高
```css
  .parent {
    position: relative;
    width: 200px;
    height: 200px;
  }
  .children {
    position: absolute;
    left: 50%;
    top: 50%;
    transform: translate(-50%, -50%);
  }
```

## 4.利用伪元素使inline-block居中
```css
  .parent {
    width: 300px;
    height: 300px;
    text-align: center;
  }
  .parent::before {
    content: '';
    display: inline-block;
    height: 100%;
    vertical-align: middle;
  }
  .children {
    display: inline-block;
    width: 100px;
    height: 100px;
    vertical-align: middle;
  }
```

## 5.table-cell使inline-block居中
```css
  .parent {
    display: table-cell;
    vertical-align: middle;
    width: 200px;
    height: 200px;
  }
  .children {
    width: 100px;
    height: 100px;
    margin: 0 auto;
  }
```

## 6.拔河效应
```css
  .parent {
    width: 300px;
    height: 300px;
    position: relative;
  }
  .children { 
    width: 100px;
    height: 100px;
    position: absolute; 
    top: 0; 
    bottom: 0; 
    left: 0;
    right: 0; 
    margin: auto;
  }
```

## 7.flex
```css
  .parent {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 300px;
    height: 300px;
    border: 1px solid;
  }

  .children {
    width: 100px;
    height: 100px;
    border: 1px solid;
  }
```
